name: travel_sage
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.17.3
  cupertino_icons: ^1.0.8
  firebase_core: any
  firebase_auth: ^4.17.7
  fl_chart: ^1.0.0
  google_fonts: 6.2.1
  shared_preferences: ^2.1.1
  provider: ^6.0.5
  image_picker: ^0.8.7+4
  intl: ^0.18.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  pie_chart: ^5.1.0
  flutter_screenutil: ^5.9.0
  shimmer: ^3.0.0
  flutter_dotenv: ^5.2.1
  firebase_core_web: ^2.17.5
  flutterfire_cli: ^1.3.1
  firebase_analytics: ^10.10.7
  firebase_crashlytics: ^3.5.7
  uuid: ^3.0.7
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo_travelsage.png