name: travel_sage
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'  # Più preciso per il range di versione

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^2.18.0  # Aggiornato all'ultima versione stabile
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.17.3
  firebase_analytics: ^10.10.7
  firebase_crashlytics: ^3.5.7
  
  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  fl_chart: ^1.0.0
  pie_chart: ^5.1.0
  flutter_map: ^6.1.0
  flutter_screenutil: ^5.9.0
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1

  # State Management & Storage
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  uuid: ^4.5.1

  # Altri
  intl: ^0.18.1
  latlong2: ^0.9.0
  image_picker: ^0.8.7+4
  flutter_dotenv: ^5.2.1
  js: ^0.6.7
  pedantic: ^1.11.0  # Considera di rimuoverlo (deprecato)
  http: ^1.4.0
  google_generative_ai: ^0.4.7
  lucide_icons: ^0.257.0 # Per icone moderne
  remixicon: ^1.4.1 # Per icone moderne
  phosphor_flutter: ^1.0.1 # Per icone moderne
  font_awesome_flutter: ^10.5.0  # Per icone più ricche
  animated_background: ^2.0.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutterfire_cli: ^1.3.1  # Spostato in dev_dependencies

flutter:
  uses-material-design: true
  assets:
    - assets/logo_travelsage.png
    - assets/Travelsage.png
    - assets/animations/splash_travel.json
    - .env  # Aggiunto il file .env agli assets

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_travelsage.png"