// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbmXGUoGFCDheDVTj0hw-wcyMPw98w23E',
    appId: '1:1051759939227:web:a17725fc335186e75d003e',
    messagingSenderId: '1051759939227',
    projectId: 'travelsage-2fbbc',
    authDomain: 'travelsage-2fbbc.firebaseapp.com',
    storageBucket: 'travelsage-2fbbc.firebasestorage.app',
    measurementId: 'G-BVR6GRSVNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWBu_dTZCy_mRmooX5lkGwLLseIXLKwEs',
    appId: '1:1051759939227:android:d7927544336b17aa5d003e',
    messagingSenderId: '1051759939227',
    projectId: 'travelsage-2fbbc',
    storageBucket: 'travelsage-2fbbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR1eAsEEGRkkcu5rQ5819K3_5wJqqK9v4',
    appId: '1:1051759939227:ios:0b75a102a323b0b55d003e',
    messagingSenderId: '1051759939227',
    projectId: 'travelsage-2fbbc',
    storageBucket: 'travelsage-2fbbc.firebasestorage.app',
    iosBundleId: 'com.example.travelSage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR1eAsEEGRkkcu5rQ5819K3_5wJqqK9v4',
    appId: '1:1051759939227:ios:0b75a102a323b0b55d003e',
    messagingSenderId: '1051759939227',
    projectId: 'travelsage-2fbbc',
    storageBucket: 'travelsage-2fbbc.firebasestorage.app',
    iosBundleId: 'com.example.travelSage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbmXGUoGFCDheDVTj0hw-wcyMPw98w23E',
    appId: '1:1051759939227:web:b34f7d629a4d79935d003e',
    messagingSenderId: '1051759939227',
    projectId: 'travelsage-2fbbc',
    authDomain: 'travelsage-2fbbc.firebaseapp.com',
    storageBucket: 'travelsage-2fbbc.firebasestorage.app',
    measurementId: 'G-RJZKZXNDNW',
  );
}
